// Postman Collection v2.1 generator for Clear
import { ClearFile, ApiBlock, ApiRoute, Property, Value } from '../ast.js'

function getStringValue(prop: Property | undefined): string | undefined {
  if (!prop) return undefined
  return prop.value?.type === 'string' ? prop.value.value : undefined
}

export function generatePostmanCollection(ast: ClearFile): string {
  const infoName = getStringValue(ast.product.properties.find(p => p.key === 'name')) || ast.product.name
  const items: any[] = []
  let baseUrl = 'http://localhost:8080'

  // Check deploy config for URL hints
  const deployBlocks = ast.blocks.filter(b => b.type === 'deploy')
  for (const block of deployBlocks) {
    const b = block as any
    if (b.target?.includes('cloudflare') || b.target?.includes('worker')) {
      const domainProp = b.properties?.find((p: any) => p.key === 'domain' || p.key === 'routes')
      if (domainProp) baseUrl = `https://${domainProp.args.join(' ')}`
    }
  }

  const apiBlocks = ast.blocks.filter(b => b.type === 'api') as unknown as ApiBlock[]
  for (const block of apiBlocks) {
    const basePath = block.path || '/'
    const routes = block.routes || []
    if (routes.length === 0) continue

    const folderItems = routes.map(route => {
      const method = route.method.toUpperCase()
      const routePath = route.path || '/'
      const fullPath = basePath + (routePath.startsWith('/') ? routePath : '/' + routePath)

      const item: any = {
        name: `${method} ${routePath}`,
        request: {
          method,
          header: [{ key: 'Content-Type', value: 'application/json' }],
          url: {
            raw: `{{baseUrl}}${fullPath}`,
            host: ['{{baseUrl}}'],
            path: fullPath.split('/').filter(Boolean).map(s => s.startsWith(':') ? `:${s.slice(1)}` : s),
          },
        },
      }

      // Add request body for POST/PUT
      if (method === 'POST' || method === 'PUT') {
        const acceptProp = route.properties.find(p => p.key === 'accept')
        if (acceptProp) {
          const fields = acceptProp.args.join(' ').split(',').map(s => s.trim())
          const example: Record<string, string> = {}
          fields.forEach(f => { example[f] = f === 'email' ? 'user@example.com' : `sample_${f}` })
          item.request.body = {
            mode: 'raw',
            raw: JSON.stringify(example, null, 2),
          }
        }
      }

      return item
    })

    items.push({
      name: basePath,
      item: folderItems,
    })
  }

  const collection = {
    info: {
      name: infoName,
      description: `Auto-generated by Clear from ${ast.product.name}`,
      schema: 'https://raw.githubusercontent.com/postmanlabs/postman-collection/v2.1.0/collection.json',
    },
    variable: [{ key: 'baseUrl', value: baseUrl, type: 'string' }],
    item: items,
  }

  return JSON.stringify(collection, null, 2)
}
