import { ClearFile, Property, Value, FieldDef, TopLevelBlock, FlowStep, ScreenSection, AgentHandler, ApiRoute } from '../ast.js'

export interface CodegenOptions {
  target: 'typescript' | 'hono' | 'express' | 'fastify' | 'koa' | 'openapi' | 'postman'
  outDir?: string
}

export function generateCode(ast: ClearFile, options: CodegenOptions = { target: 'typescript' }): string {
  const parts: string[] = []

  parts.push(`// Auto-generated by Clear v0.2`)
  parts.push(`// Source: ${ast.product.name}`)
  parts.push(`// Do not edit — changes should be made to the .clear file`)
  parts.push('')

  // Generate imports
  parts.push(generateImports(ast, options))

  // Generate each block
  for (const block of ast.blocks) {
    switch (block.type) {
      case 'data':
        parts.push(generateDataBlock(block))
        break
      case 'flow':
        parts.push(generateFlowBlock(block))
        break
      case 'rule':
        parts.push(generateRuleBlock(block))
        break
      case 'screen':
        parts.push(generateScreenBlock(block))
        break
      case 'agent':
        parts.push(generateAgentBlock(block))
        break
      case 'skill':
        parts.push(generateSkillBlock(block))
        break
      case 'api':
        parts.push(generateApiBlock(block, options))
        break
      case 'event':
        parts.push(generateEventBlock(block))
        break
      case 'config':
        parts.push(generateConfigBlock(block))
        break
      case 'example':
        parts.push(generateExampleBlock(block))
        break
      case 'deploy':
        parts.push(generateDeployBlock(block, options))
        break
    }
    parts.push('')
  }

  // Generate main export
  parts.push(generateMainExport(ast))

  return parts.join('\n')
}

export function generateImports(ast: ClearFile, options: CodegenOptions): string {
  const lines: string[] = []

  if (options.target === 'hono') {
    lines.push(`import { Hono } from 'hono'`)
  } else if (options.target === 'express') {
    lines.push(`import express, { Request, Response, NextFunction } from 'express'`)
  }

  const hasFlows = ast.blocks.some(b => b.type === 'flow')
  if (hasFlows) {
    lines.push(`import { z } from 'zod'`)
  }

  const hasTimestamps = ast.blocks.some(b => {
    if (b.type === 'data') return (b as any).fields?.some((f: FieldDef) =>
      f.properties.some(p => p.key === 'type' && p.args.includes('timestamp'))
    )
    return false
  })
  if (hasTimestamps) {
    lines.push(`import { v4 as uuidv4 } from 'uuid'`)
  }

  return lines.join('\n')
}

function getPropertyValue(prop: Property): string {
  if (prop.value) {
    return renderValue(prop.value)
  }
  if (prop.args.length > 0) {
    return prop.args.map(a => {
      if (a === 'true') return 'true'
      if (a === 'false') return 'false'
      if (!isNaN(Number(a))) return a
      return `'${a.replace(/'/g, "\\'")}'`
    }).join(' ')
  }
  return 'true'
}

function renderValue(value: Value): string {
  switch (value.type) {
    case 'string':
      return `'${value.value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`
    case 'number':
      return String(value.value)
    case 'boolean':
      return value.value ? 'true' : 'false'
    case 'list':
      return `[${value.value.map(v => renderValue(v)).join(', ')}]`
    case 'special':
      if (value.keyword === 'now') return 'new Date().toISOString()'
      if (value.keyword === 'null') return 'null'
      if (value.keyword === 'auto') return 'undefined  // auto-generated'
      return 'undefined'
    case 'env':
      return `process.env['${value.name}'] ?? ''`
    case 'identifier':
      return value.value
    case 'reference':
      return value.name
    case 'map':
      return `{ ${value.value.map(e => `${e.key}: ${renderValue(e.value)}`).join(', ')} }`
  }
}

function generateDataBlock(block: any): string {
  const lines: string[] = []
  lines.push(`// Data: ${block.name}`)
  lines.push(`export interface ${block.name} {`)

  for (const field of block.fields as FieldDef[]) {
    const tsType = inferTypeScriptType(field)
    const optional = !field.properties.some(p => p.key === 'required' && p.args.includes('true'))
    lines.push(`  ${field.name}${optional ? '?' : ''}: ${tsType}`)
  }

  lines.push('}')
  lines.push('')
  lines.push(`export function create${block.name}(data: Partial<${block.name}>): ${block.name} {`)
  lines.push(`  const defaults: Record<string, any> = {`)

  for (const field of block.fields) {
    const defaultProp = field.properties.find((p: Property) => p.key === 'default')
    if (defaultProp) {
      lines.push(`    ${field.name}: ${getPropertyValue(defaultProp)},`)
    }
    const typeProp = field.properties.find((p: Property) => p.key === 'type')
    if (typeProp && typeProp.args[0] === 'timestamp' && !defaultProp) {
      // Some timestamps default to now
      if (field.name === 'created_at' || field.name === 'synced_at') {
        lines.push(`    ${field.name}: new Date().toISOString(),`)
      }
    }
  }

  lines.push('  }')
  lines.push('  return { ...defaults, ...data } as unknown as ' + block.name)
  lines.push('}')

  return lines.join('\n')
}

function inferTypeScriptType(field: FieldDef): string {
  const typeProp = field.properties.find(p => p.key === 'type')
  if (!typeProp) return 'unknown'

  const typeStr = typeProp.args.join(' ')

  // Handle "list of X"
  if (typeStr.startsWith('list of ')) {
    const innerType = typeStr.slice(8).trim()
    if (['string', 'integer', 'float', 'boolean'].includes(innerType)) {
      return `${mapPrimitiveType(innerType)}[]`
    }
    return `${innerType}[]`
  }

  // Handle "map"
  if (typeStr === 'map') {
    return 'Record<string, any>'
  }

  // Handle "enum"
  if (typeStr === 'enum') {
    const optionsProp = field.properties.find(p => p.key === 'options')
    if (optionsProp && optionsProp.value?.type === 'list') {
      const vals = optionsProp.value.value.map(v => `'${(v as any).value}'`)
      return vals.join(' | ')
    }
    return 'string'
  }

  // Handle "reference X"
  if (typeStr.startsWith('reference ')) {
    return typeStr.slice(10).trim()
  }

  return mapPrimitiveType(typeStr)
}

function mapPrimitiveType(type: string): string {
  switch (type) {
    case 'string': return 'string'
    case 'integer': return 'number'
    case 'float': return 'number'
    case 'boolean': return 'boolean'
    case 'timestamp': return 'string'
    case 'uuid': return 'string'
    case 'url': return 'string'
    case 'email': return 'string'
    default: return type
  }
}

function generateFlowBlock(block: any): string {
  const lines: string[] = []
  lines.push(`// Flow: ${block.name}`)
  lines.push(`export async function ${camelCase(block.name)}(context: Record<string, any> = {}): Promise<Record<string, any>> {`)
  lines.push(`  const ctx: Record<string, any> = { ...context }`)
  lines.push('  const errors: string[] = []')
  lines.push('')

  for (const step of block.steps as FlowStep[]) {
    lines.push(`  // Step: ${step.name}`)
    lines.push(`  console.log('[${block.name}] Step: ${step.name}')`)
    lines.push(`  try {`)

    for (const prop of step.properties) {
      const code = generateFlowStatement(prop)
      if (code) lines.push(`    ${code}`)
    }

    lines.push(`  } catch (err: any) {`)
    lines.push(`    errors.push('Step ${step.name}: ' + err.message)`)
    lines.push(`    throw new Error(\`[${block.name}] Failed at step '${step.name}': \${err.message}\`)`)
    lines.push(`  }`)
    lines.push('')
  }

  lines.push('  if (errors.length > 0) {')
  lines.push('    throw new Error(`Flow ${block.name} completed with errors: ${errors.join(\', \')}`)')
  lines.push('  }')
  lines.push('')
  lines.push('  return ctx')
  lines.push('}')

  return lines.join('\n')
}

function generateFlowStatement(prop: Property): string | null {
  switch (prop.key) {
    case 'check':
      return `if (!(${prop.args.join(' ')})) { throw new Error('Check failed: ${prop.args.join(' ')}') }`
    case 'set':
      if (prop.args.length >= 2) {
        return `ctx['${prop.args[0]}'] = ${prop.args.slice(1).join(' ')}`
      }
      return null
    case 'insert':
      return `// TODO: Insert into ${prop.args.join(' ')}`
    case 'update':
      return `// TODO: Update ${prop.args.join(' ')}`
    case 'delete':
      return `// TODO: Delete ${prop.args.join(' ')}`
    case 'send':
      return `// TODO: Send ${prop.args.join(' ')}`
    case 'create':
      return `// TODO: Create ${prop.args.join(' ')}`
    case 'fetch':
      return `// TODO: Fetch ${prop.args.join(' ')}`
    case 'paginate':
      return `// TODO: Paginate through ${prop.args.join(' ')}`
    case 'route':
      return `// TODO: Route to ${prop.args.join(' ')}`
    case 'retry':
      return `// TODO: Retry ${prop.args.join(' ')}`
    case 'log':
      return `console.log('${prop.args.join(' ')}')`
    case 'notify':
      return `// TODO: Notify ${prop.args.join(' ')}`
    case 'map':
      return `// TODO: Map ${prop.args.join(' ')}`
    case 'merge':
      return `// TODO: Merge ${prop.args.join(' ')}`
    case 'generate':
      return `// TODO: Generate ${prop.args.join(' ')}`
    case 'include':
      return `// TODO: Include ${prop.args.join(' ')}`
    case 'trigger':
      return `// TODO: Handle trigger: ${prop.args.join(' ')}`
    case 'classify':
      return `// TODO: Classify ${prop.args.join(' ')}`
    case 'search':
      return `// TODO: Search ${prop.args.join(' ')}`
    case 'draft':
      return `// TODO: Draft ${prop.args.join(' ')}`
    case 'extract':
      return `// TODO: Extract ${prop.args.join(' ')}`
    case 'calculate':
      return `// TODO: Calculate ${prop.args.join(' ')}`
    case 'deduplicate':
      return `// TODO: Deduplicate ${prop.args.join(' ')}`
    case 'upsert':
      return `// TODO: Upsert ${prop.args.join(' ')}`
    case 'filter':
      return `// TODO: Filter ${prop.args.join(' ')}`
    case 'group':
      return `// TODO: Group ${prop.args.join(' ')}`
    case 'add':
      if (prop.args.includes('points')) {
        return `ctx['score'] = (ctx['score'] ?? 0) + ${prop.args[1] ?? 0}`
      }
      return `// TODO: Add ${prop.args.join(' ')}`
    default:
      return `// ${prop.key}: ${prop.args.join(' ')}`
  }
}

function generateRuleBlock(block: any): string {
  const lines: string[] = []
  lines.push(`// Rule: ${block.name}`)
  lines.push(`export function apply${block.name}(data: Record<string, any>): { valid: boolean; errors: string[] } {`)
  lines.push(`  const errors: string[] = []`)
  lines.push('')

  for (const prop of block.properties) {
    if (prop.key === 'apply') continue
    if (prop.key === 'require') {
      lines.push(`  // require: ${prop.args.join(' ')}`)
      lines.push(`  // TODO: Implement validation rule: ${prop.args.join(' ')}`)
    } else if (prop.key === 'add') {
      lines.push(`  // scoring: ${prop.args.join(' ')}`)
    } else if (prop.key === 'on') {
      lines.push(`  // on violation: ${prop.args.join(' ')}`)
    }
  }

  lines.push('')
  lines.push('  return { valid: errors.length === 0, errors }')
  lines.push('}')

  return lines.join('\n')
}

function generateScreenBlock(block: any): string {
  const lines: string[] = []
  lines.push(`// Screen: ${block.name}`)

  // Get the title from properties
  const titleProp = block.properties.find((p: Property) => p.key === 'title')
  const title = titleProp ? getPropertyValue(titleProp) : `'${block.name}'`

  lines.push('// This is a UI screen definition.')
  lines.push('// To render, use a Clear UI runtime or generate React/HTML from this spec.')
  lines.push(`export const ${block.name}Screen = {`)
  lines.push(`  name: '${block.name}',`)
  lines.push(`  title: ${title},`)

  const layoutProp = block.properties.find((p: Property) => p.key === 'layout')
  if (layoutProp) lines.push(`  layout: ${getPropertyValue(layoutProp)},`)

  if (block.sections && block.sections.length > 0) {
    lines.push(`  sections: [`)
    for (const section of block.sections as ScreenSection[]) {
      lines.push(`    {`)
      lines.push(`      name: '${section.name}',`)
      let showProp = section.properties.find((p: Property) => p.key === 'show')
      if (showProp) {
        lines.push(`      show: '${showProp.args.join(' ')}',`)
        const asProp = section.properties.find((p: Property) => p.key === 'show' && showProp !== p)
        // Check for "as" pattern
        const asIdx = showProp.args.indexOf('as')
        if (asIdx >= 0 && asIdx + 1 < showProp.args.length) {
          lines.push(`      as: '${showProp.args[asIdx + 1]}',`)
        }
      }
      // Add remaining properties
      for (const p of section.properties) {
        if (p.key !== 'show') {
          lines.push(`      ${p.key}: ${getPropertyValue(p)},`)
        }
      }
      lines.push(`    },`)
    }
    lines.push(`  ]`)
  }

  lines.push('} as const')

  return lines.join('\n')
}

function generateAgentBlock(block: any): string {
  const lines: string[] = []
  lines.push(`// Agent: ${block.name}`)

  const roleProp = block.properties.find((p: Property) => p.key === 'role')
  const personalityProp = block.properties.find((p: Property) => p.key === 'personality')
  const goalProp = block.properties.find((p: Property) => p.key === 'goal')

  lines.push(`export const ${block.name} = {`)
  lines.push(`  name: '${block.name}',`)
  if (roleProp) lines.push(`  role: ${getPropertyValue(roleProp)},`)
  if (personalityProp) lines.push(`  personality: ${getPropertyValue(personalityProp)},`)
  if (goalProp) lines.push(`  goal: ${getPropertyValue(goalProp)},`)

  if (block.handlers && block.handlers.length > 0) {
    lines.push(`  handlers: {`)
    for (const handler of block.handlers as AgentHandler[]) {
      lines.push(`    '${handler.event}': async (ctx: Record<string, any>) => {`)
      for (const prop of handler.properties) {
        const code = generateFlowStatement(prop)
        if (code) lines.push(`      ${code}`)
      }
      lines.push(`    },`)
    }
    lines.push(`  },`)
  }

  lines.push('} as const')

  return lines.join('\n')
}

function generateSkillBlock(block: any): string {
  const lines: string[] = []
  lines.push(`// Skill: ${block.name}`)
  lines.push(`export class ${block.name} {`)

  // Generate input/output types
  const inputProps = block.properties.filter((p: Property) => p.key === 'input')
  const outputProps = block.properties.filter((p: Property) => p.key === 'output')

  if (inputProps.length > 0 || outputProps.length > 0) {
    lines.push(`  static async execute(params: {`)
    for (const prop of inputProps) {
      const parts = prop.args.join(' ')
      const name = parts.split(' ')[0]
      const rest = parts.slice(name.length).trim()
      lines.push(`    ${name}: ${rest ? inferSkillType(rest) : 'unknown'},`)
    }
    lines.push(`  }): Promise<{`)
    for (const prop of outputProps) {
      const rest = prop.args.join(' ')
      const name = rest.split(' ')[0]
      const restType = rest.slice(name.length).trim()
      lines.push(`    ${name}: ${restType ? inferSkillType(restType) : 'unknown'},`)
    }
    lines.push(`  }> {`)

    // Generate method body
    const methodProp = block.properties.find((p: Property) => p.key === 'method')
    if (methodProp) {
      for (const child of methodProp.children) {
        const code = generateFlowStatement(child)
        if (code) lines.push(`    ${code}`)
      }
    }

    lines.push(`    throw new Error('Skill ${block.name}.execute not implemented')`)
    lines.push(`  }`)
  }

  lines.push('}')

  return lines.join('\n')
}

function inferSkillType(typeStr: string): string {
  if (typeStr.startsWith('string')) return 'string'
  if (typeStr.startsWith('integer') || typeStr.startsWith('float')) return 'number'
  if (typeStr.startsWith('boolean')) return 'boolean'
  if (typeStr.startsWith('list')) return 'any[]'
  if (typeStr.startsWith('map')) return 'Record<string, any>'
  return 'any'
}

function generateApiBlock(block: any, options: CodegenOptions): string {
  const lines: string[] = []

  if (block.protocol === 'REST') {
    const routeName = (block.path || '/').replace(/[^a-zA-Z0-9]/g, '_')
    lines.push(`// API: ${block.protocol} ${block.path}`)
    if (options.target === 'hono') {
      lines.push(`export function register${block.protocol}Routes_${routeName}(app: Hono): void {`)
    } else if (options.target === 'express') {
      lines.push(`export function register${block.protocol}Routes_${routeName}(app: express.Application): void {`)
    } else {
      lines.push(`export function register${block.protocol}Routes_${routeName}(): Record<string, any>[] {`)
      lines.push(`  const routes: Record<string, any>[] = []`)
    }

    for (const route of block.routes as ApiRoute[]) {
      const method = route.method.toUpperCase()
      const routePath = route.path || '/'

      // Parse the route path for parameters like /:id
      const tsPath = routePath.replace(/:(\w+)/g, '{$1}')

      if (options.target === 'typescript') {
        lines.push(`  routes.push({ method: '${method}', path: '${routePath}', handler: async (req: any, res: any) => {`)
        for (const prop of route.properties) {
          if (prop.key === 'return') {
            lines.push(`    return '${prop.args.join(' ')}'  // TODO: implement return`)
          } else if (prop.key === 'error') {
            lines.push(`    // error: ${prop.args.join(' ')}`)
          } else if (prop.key === 'accept') {
            lines.push(`    // accept: ${prop.args.join(' ')}`)
          } else if (prop.key === 'paginate') {
            lines.push(`    // paginate: ${prop.args.join(' ')}`)
          } else if (prop.key === 'set') {
            lines.push(`    // set: ${prop.args.join(' ')}`)
          } else if (prop.key === 'include') {
            lines.push(`    // include: ${prop.args.join(' ')}`)
          } else if (prop.key === 'remove') {
            lines.push(`    // remove: ${prop.args.join(' ')}`)
          } else if (prop.key === 'filter') {
            lines.push(`    // filter: ${prop.args.join(' ')}`)
          } else if (prop.key === 'sort') {
            lines.push(`    // sort: ${prop.args.join(' ')}`)
          } else if (prop.key === 'validate') {
            lines.push(`    // validate: ${prop.args.join(' ')}`)
          } else if (prop.key === 'status') {
            const statusVal = getPropertyValue(prop)
            if (statusVal !== 'true') {
              lines.push(`    res.status(${statusVal})`)
              lines.push(`    return`)
            }
          }
        }
        lines.push(`  } })`)
      }
    }

    if (options.target === 'typescript') {
      lines.push(`  return routes`)
    }
    lines.push('}')
  } else if (block.protocol === 'MCP') {
    const mcpName = block.path && block.path !== '/' ? block.path.replace(/[^a-zA-Z0-9]/g, '_') : 'MCPServer'
    lines.push(`// MCP Server: ${block.path}`)
    lines.push(`export const ${mcpName}Tools = {`)
    for (const route of block.routes as ApiRoute[]) {
      if (route.method === 'tool') {
        lines.push(`  ${route.path}: {`)
        lines.push(`    description: '${route.properties.find((p: Property) => p.key === 'description')?.args.join(' ') ?? ''}',`)
        lines.push(`    execute: async (params: any) => {`)
        lines.push(`      throw new Error('Tool ${route.path} not implemented')`)
        lines.push(`    },`)
        lines.push(`  },`)
      }
    }
    lines.push('} as const')
  }

  return lines.join('\n')
}

function generateEventBlock(block: any): string {
  const lines: string[] = []
  lines.push(`// Event: ${block.name}`)

  const payloadProp = block.properties.find((p: Property) => p.key === 'payload')
  if (payloadProp) {
    lines.push(`export type ${block.name}Payload = {`)
    for (const field of payloadProp.args) {
      lines.push(`  ${field}: any,`)
    }
    lines.push('}')
  }

  lines.push(`export function emit${block.name}(payload: any): void {`)
  lines.push(`  console.log('[Event] ${block.name}:', payload)`)
  lines.push(`  // TODO: Dispatch to registered handlers`)
  lines.push('}')

  return lines.join('\n')
}

function generateConfigBlock(block: any): string {
  const lines: string[] = []
  lines.push(`// Config: ${block.name}`)
  lines.push(`export const ${block.name}Config = {`)

  for (const prop of block.properties) {
    if (prop.args.length > 0 && prop.args[0] === 'from' && prop.args[1] === 'env') {
      const envName = prop.args[2]
      lines.push(`  get ${prop.key}(): string { return process.env['${envName}'] ?? '' },`)
    } else {
      lines.push(`  ${prop.key}: ${getPropertyValue(prop)},`)
    }
  }

  lines.push('} as const')
  return lines.join('\n')
}

function generateExampleBlock(block: any): string {
  const lines: string[] = []
  lines.push(`// Example: ${block.name}`)
  lines.push(`// This is a test/documentation case.`)
  lines.push(`// In a test framework: \`describe('${block.name.replace(/'/g, "\\'")}', ...)\``)
  lines.push(`export const example_${block.name.replace(/[^a-zA-Z0-9]/g, '_')}_ = {`)
  lines.push(`  description: '${block.name.replace(/'/g, "\\'")}',`)

  const givenProps = block.properties.filter((p: Property) => p.key === 'given')
  const whenProps = block.properties.filter((p: Property) => p.key === 'when')
  const thenProps = block.properties.filter((p: Property) => p.key === 'then')

  if (givenProps.length > 0) {
    lines.push(`  given: [`)
    for (const p of givenProps) lines.push(`    '${p.args.join(' ').replace(/'/g, "\\'")}',`)
    lines.push(`  ],`)
  }
  if (whenProps.length > 0) {
    for (const p of whenProps) lines.push(`  when: '${p.args.join(' ').replace(/'/g, "\\'")}',`)
  }
  if (thenProps.length > 0) {
    lines.push(`  then: [`)
    for (const p of thenProps) lines.push(`    '${p.args.join(' ').replace(/'/g, "\\'")}',`)
    lines.push(`  ],`)
  }

  lines.push('} as const')
  return lines.join('\n')
}

function generateDeployBlock(block: any, options: CodegenOptions): string {
  const lines: string[] = []
  lines.push(`// Deploy target: ${block.target}`)
  lines.push(`export const deployConfig = {`)
  lines.push(`  target: '${block.target}',`)

  for (const prop of block.properties) {
    lines.push(`  ${prop.key}: ${getPropertyValue(prop)},`)
  }

  lines.push('} as const')
  return lines.join('\n')
}

function generateMainExport(ast: ClearFile): string {
  const lines: string[] = []
  lines.push('// Main export')
  lines.push(`export const product = ${JSON.stringify(ast.product.name)}`)
  lines.push('')
  lines.push(`export default {`)
  lines.push(`  name: ${JSON.stringify(ast.product.name)},`)

  const dataBlocks = ast.blocks.filter(b => b.type === 'data')
  if (dataBlocks.length > 0) {
    lines.push(`  schemas: { ${dataBlocks.map(b => (b as any).name).join(', ')} },`)
  }

  const flowBlocks = ast.blocks.filter(b => b.type === 'flow')
  if (flowBlocks.length > 0) {
    lines.push(`  flows: { ${flowBlocks.map(b => (b as any).name).join(', ')} },`)
  }

  lines.push('}')
  return lines.join('\n')
}

function camelCase(str: string): string {
  return str.charAt(0).toLowerCase() + str.slice(1)
}
